services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_pass
      POSTGRES_DB: task_db
    ports:
      - "5879:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/sql:/docker-entrypoint-initdb.d  
volumes:
  db_data:
